//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentDemo.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public int UserId { get; set; }
        [Required]
        [Display(Name = "User Name")]
        public string Username { get; set; }
        [Required]
      
        public string Password { get; set; }
        [Required]
        [RegularExpression(@"^[a-zA-Z\s]+$")]
        [Display(Name = "First Name")]
        public string Firstname { get; set; }
        [Required]
        [RegularExpression(@"^[a-zA-Z\s]+$")]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
    }
}
